# Generated by Django 4.2 on 2023-05-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='numero',
        ),
        migrations.DeleteModel(
            name='Queja',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
