# Generated by Django 4.2 on 2023-05-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionQuejasAPP', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='entrega',
            field=models.BooleanField(default=False),
        ),
    ]
