# Generated by Django 4.2 on 2023-05-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionQuejasAPP', '0004_respuesta_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='fechaT',
        ),
        migrations.AddField(
            model_name='queja',
            name='fechaT',
            field=models.DateTimeField(null='True'),
            preserve_default='True',
        ),
    ]
