# Generated by Django 4.2 on 2023-05-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionQuejasAPP', '0006_alter_queja_fechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='casoPrensa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='queja',
            name='clasificacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='queja',
            name='entidadAfectada',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='queja',
            name='modalidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='queja',
            name='nombre_apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='queja',
            name='procedencia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='queja',
            name='via',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='conclusion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='responsable',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='satisfaccion',
            field=models.CharField(max_length=50),
        ),
    ]
